services:

  postgres:
    container_name: learn-skills-postgres
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_USER: learn_skills
      POSTGRES_PASSWORD: learn_skills
      POSTGRES_DB: learn_skills
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  phppgadmin:
    container_name: learn-skills-phppgadmin
    image: bitnami/phppgadmin-archived
    restart: on-failure
    environment:
      DATABASE_HOST: postgres
    ports:
      - "${PHPPGADMIN_PORT:-9080}:8080"

  assets:
    container_name: learn-skills-assets
    user: "$UID:$GID"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ".:/app:rw"
      - "build:/data/public/build/"
    ports:
      - ${ENCORE_PORT_HTTP:-8080}:8080

  php:
    container_name: learn-skills-php
    restart: on-failure
    user: "$UID:$GID"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - assets
      - postgres
    volumes:
      - ".:/app:rw" # Mount the current directory to /app in read-write mode
    environment:
      DATABASE_URL: "pgsql://learn_skills:learn_skills@postgres:5432/learn_skills" # Ensure this matches your database settings

  nginx:
    container_name: learn-skills-nginx
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - ".:/app:ro" # Mount the current directory to /app in read-only mode
      - "build:/data/public/build/"
    ports:
      - ${PHP_PORT_HTTP:-80}:80

  mailpit:
    container_name: learn-skills-mailpit
    image: axllent/mailpit:latest
    restart: on-failure
    ports:
      - "8025:8025" # Interface Web de Mailpit
      - "1025:1025" # Port SMTP pour envoyer des e-mails
volumes:
  build:
  db:
