# build dev assets
FROM node:23-alpine

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances et lancer le processus de développement
CMD ["sh", "-c", "npm install && npm run watch"]